<?php

namespace Drupal\obw_utilities\Plugin\views\filter;

use Drupal\taxonomy\Plugin\views\filter\TaxonomyIndexTid;

/**
 * Multiple choice separate filter.
 *
 * @ingroup views_filter_handlers
 *
 * @ViewsFilter("tax_sep_multi_choice_filter")
 */
class TaxSeparateMultiChoiceViewsFilter extends TaxonomyIndexTid {

  public function query() {
    parent::query(); // TODO: Change the autogenerated stub
    foreach ($this->query->where as &$conditions) {
      if ($conditions['conditions'][0]['field'] != 'node_field_data.status') {
        $conditions['type'] = "OR";
      }
    }
  }

}
